name: generate-documentation

on: [push]

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: zhulik/redis-action@1.1.0
      with:
        redis version: "5"
        number of databases: 1
    - name: Set up as module
      run: |
        git config --global user.name "${{ secrets.NAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
        npm install
        npm version patch
        mkdir /tmp/project
        cd /tmp/project
        npm init -y
        npm install faker puppeteer@2.1.1 @userdashboard/dashboard @userdashboard/organizations @userdashboard/storage-redis
        npm install -g mocha
        rm node_modules/@userdashboard/organizations/*.js
        rm -rf node_modules/@userdashboard/organizations/src
        cp /home/runner/work/organizations/organizations/*.js node_modules/@userdashboard/organizations
        cp -R /home/runner/work/organizations/organizations/src/ node_modules/@userdashboard/organizations/src/
        echo "global.applicationPath = __dirname" > main.js
        PACKAGE=`cat package.json`
        PACKAGE=${PACKAGE/\"description\"\: \"\"/\"dashboard\": \{ \"modules\"\: \[\"@userdashboard/organizations\"\] \}}
        echo $PACKAGE > package.json
    - name: Generate documentation
      run: |
        mocha --grep returns --retries 2 --file main.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/organizations/**/*.test.js"
        mocha --grep screenshots --retries 2 --file main.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/organizations/**/*.test.js"
      working-directory: "/tmp/project"
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE: "@userdashboard/storage-redis"
        REDIS_URL: "redis://localhost:6379"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false   
        GENERATE_RESPONSE: true
        GENERATE_SCREENSHOTS: true
        RESPONSE_PATH: "/home/runner/work/organizations/organizations/documentation"
        SCREENSHOT_PATH: "/home/runner/work/organizations/organizations/documentation/screenshots"
        SCREENSHOT_LANGUAGES: "en,es,af,bg,pl,tr,hu,vi"
        LOG_LEVEL: "info,error,warn,log"
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        external_repository: "userdashboard/userdashboard.github.io"
        personal_token: ${{ secrets.DOCUMENTATION_PAT }}
        publish_dir: documentation
        publish_branch: master
        keep_files: true
