name: test-and-publish

on: [push]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: zhulik/redis-action@1.1.0
      with:
        redis version: '5'
        number of databases: 1
    - name: Set up as module
      run: |
        git config --global user.name "${{ secrets.NAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
        npm install
        npm install @userdashboard/dashboard --no-save
        npm version patch
        mkdir /tmp/project
        cd /tmp/project
        npm init -y
        npm install faker puppeteer@2.1.1 @userdashboard/dashboard @userdashboard/organizations @userdashboard/storage-redis
        npm install -g mocha standard
        rm node_modules/@userdashboard/organizations/*.js
        rm -rf node_modules/@userdashboard/organizations/src
        rm -rf node_modules/@userdashboard/organizations/languages
        cp /home/runner/work/organizations/organizations/*.js node_modules/@userdashboard/organizations
        cp -R /home/runner/work/organizations/organizations/languages/ node_modules/@userdashboard/organizations/languages/
        cp -R /home/runner/work/organizations/organizations/src/ node_modules/@userdashboard/organizations/src/
        echo "global.applicationPath = __dirname" > main.js
        PACKAGE=`cat package.json`
        PACKAGE=${PACKAGE/\"description\"\: \"\"/\"dashboard\": \{ \"modules\"\: \[\"@userdashboard/organizations\"\] \}}
        echo $PACKAGE > package.json
        git clone https://github.com/userdashboard/localization.git /tmp/localize
        cd /tmp/localize
        npm install @userdashboard/dashboard
        for LOCALE in `cat languages`; do
          node clean-cache.js "$LOCALE" /home/runner/work/localization/localization/project/organizations $HERE
          node localize.js "$LOCALE" $HERE
        done
    - name: Lint (standard.js)
      run: standard src
    - name: Test (redis)
      run: |
        mocha --retries 2 --file main.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/**/{,!(public)}/*.test.js" | tee /home/runner/work/organizations/organizations/test.txt
        TESTS=`cat /home/runner/work/organizations/organizations/tests.txt`
        if [[ "$TESTS" == *" 1)"* ]]; then
          exit 1
        fi
        cat /home/runner/work/organizations/organizations/package.json
      working-directory: '/tmp/project'
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE: "@userdashboard/storage-redis"
        REDIS_URL: "redis://localhost:6379"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
    - name: Generate supporting texts
      run: node main.js
      working-directory: /home/runner/work/organizations/organizations/
      env:
        NODE_ENV: sitemap
        EXIT_ON_START: true
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
    - name: Publish to Github
      uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Automatically regenerated against current version
        branch: ${{ github.head_ref }}
        commit_options: '--no-verify --signoff'
        repository: .
    - name: Publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
